random-xs:
  plsh:
    docker-tag: neurips23-streaming-plsh
    module: neurips23.streaming.plsh.plsh
    constructor: PLSH
    base-args: [ "@metric" ]
    run-groups:
      base:
        args: |
          [{
            "k": 8,
            "m": 60,
            "num_threads": 1,
            "merge_threshold": 50000
          }]
        query-args: |
          [{
            "K": 10
          }]